#!/bin/bash
# Reset password via GoTrue Admin API
# This is the proper way to set passwords in GoTrue

cd ~/HealApp-Web

EMAIL="nazardubnak@gmail.com"
NEW_PASSWORD="dn2907200"
API_KEY="kSW54FYXXViT8ifRUef7DqfNXYp687ecDjdp8HSggodn1To2638caajJMoA48qze"
AUTH_URL="http://localhost:54326"

echo "Attempting to reset password via GoTrue Admin API..."

# First, get the user ID
USER_ID=$(docker compose exec -T db psql -U postgres -d postgres -t -A -c "SELECT id FROM auth.users WHERE email = '$EMAIL';")

if [ -z "$USER_ID" ]; then
  echo "ERROR: User not found"
  exit 1
fi

echo "User ID: $USER_ID"

# Try to update password via Admin API (requires service_role key)
# Note: This might not work without service_role key, but let's try

# Alternative: Use SQL to update password with a hash generated by GoTrue's method
# But since we can't easily call GoTrue's internal methods, let's try a different approach:

# Use the working hash format from another user as a template
WORKING_HASH=$(docker compose exec -T db psql -U postgres -d postgres -t -A -c "SELECT encrypted_password FROM auth.users WHERE email = 'kondratjewa.ev@mail.ru' LIMIT 1;")

echo "Working hash format: ${WORKING_HASH:0:30}..."

# The issue might be that GoTrue expects a specific format
# Let's try using Python bcrypt with the exact same parameters as GoTrue uses
# GoTrue uses bcrypt with rounds=10 and prefix $2a$

cd /tmp
python3 << 'PYTHON_SCRIPT'
import bcrypt

password = b"dn2907200"
# Generate salt with $2a$ prefix and 10 rounds (same as GoTrue)
salt = bcrypt.gensalt(rounds=10, prefix=b"2a")
hashed = bcrypt.hashpw(password, salt)
print(hashed.decode('utf-8'))
PYTHON_SCRIPT

echo ""
echo "If the hash above looks correct, we can update it in the database."

